In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [ ]:
x=[10,20,30,40]
y=[100,200,300,400]

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

### Basic Calculations using Numpy

In [7]:
a=np.array([10,20,30,40])
b=np.array([100,200,300,400])
a,b

(array([10, 20, 30, 40]), array([100, 200, 300, 400]))

In [10]:
type(a),type(b)

(numpy.ndarray, numpy.ndarray)

In [11]:
a**2

array([ 100,  400,  900, 1600])

In [12]:
b+10


array([110, 210, 310, 410])

In [13]:
a+b

array([110, 220, 330, 440])

In [14]:
a-b

array([ -90, -180, -270, -360])

In [15]:
a*b

array([ 1000,  4000,  9000, 16000])

In [16]:
a/b

array([0.1, 0.1, 0.1, 0.1])

In [18]:
np.sqrt(a),np.sqrt(b)

(array([3.16227766, 4.47213595, 5.47722558, 6.32455532]),
 array([10.        , 14.14213562, 17.32050808, 20.        ]))

In [19]:
np.log10(a),np.log10(b)

(array([1.        , 1.30103   , 1.47712125, 1.60205999]),
 array([2.        , 2.30103   , 2.47712125, 2.60205999]))

### Calculate Algebric Equation 

In [9]:
x=np.array([2,5,7,4])
y=np.array([10,3,6,8])
3*x+4*y

array([46, 27, 45, 44])

In [11]:
3*x**x+4*x*y+3

array([     95,    9438, 2470800,     899])

In [12]:
np.abs(y)

array([10,  3,  6,  8])

#### Shows type,Datatype,and No. of Dimensions,Display No. of elements

In [8]:
type(x),x.dtype,x.ndim,x.shape

(numpy.ndarray, dtype('int32'), 1, (4,))

In [14]:
a=np.array([10,20,45,34,79,20,45,50])
a.dtype,a.ndim,a.shape

(dtype('int32'), 1, (8,))

### Generate a sequence of Numbers(np.arange([start,stop,step]

In [24]:
s= np.arange(10 )
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
s= np.arange(1,11,2)
type(s),s.shape,s.ndim
s

array([1, 3, 5, 7, 9])

In [29]:
s= np.arange(1,11,2)
type(s),s.shape,s.ndim

(numpy.ndarray, (5,), 1)

In [3]:
s=np.linspace(2,10,10)
s

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

### In between 0 to 1 we have to generate 100 Numbers

In [6]:
s=np.linspace(0,1,100)
s

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747