In [1]:
import numpy as np

### np.matrixlib.matrix is noting but a subpackage
Matrix is always a 2 Dimension, Not an N Dimension
Here every row must be seperated by a semicolon
### It is more useful in Linear Vectors and Deep Learning

In [7]:
 m1= np.matrixlib.matrix('1,2,3,4;5,6,7,8')
m1

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [8]:
 m1= np.matrixlib.matrix('1,2,3,4;5,6,7,8')
m2= np.matrixlib.matrix('10,20;30,40;50,60;70,80')
m1.shape,m2.shape

((2, 4), (4, 2))

In [10]:
m1,m2

(matrix([[1, 2, 3, 4],
         [5, 6, 7, 8]]),
 matrix([[10, 20],
         [30, 40],
         [50, 60],
         [70, 80]]))

### Here we do not need to use dot product to Multiply m1 and m2
### we can directly multiply here

In [9]:
m1*m2

matrix([[ 500,  600],
        [1140, 1400]])

In [11]:
type(m1)

numpy.matrix

In [12]:
m1.ndim

2

In [14]:
np.matrix('1,2,3,4')

matrix([[1, 2, 3, 4]])

In [15]:
np.matrix('1,2,3,4').shape

(1, 4)