In [1]:
import numpy as np

In [2]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
x=np.arange(1,11)
x.ndim,x.shape,x.dtype

(1, (10,), dtype('int32'))

In [5]:
x[1:5:2]

array([2, 4])

## Creating 2D Array

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a.ndim,a.dtype,a.shape

(2, dtype('int32'), (4, 3))

### Creating another 2D Array with 2 elements in it

In [8]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

### Operations in 2 D Array

In [ ]:
x*y

### dot() This function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication

In [10]:
x.dot(y)

array([[19, 22],
       [43, 50]])

### Reshaping means changing the shape of an array.
#### The shape of an array is the number of elements in each dimension.

In [21]:
m= np.arange(1,11).reshape(5,2)
m

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
m= np.arange(1,26).reshape(5,5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### We can reshape the Sequence only when the Dimensions are Multiples of the nth Sequence Number 

In [22]:
x=np.arange(1,7).reshape(1,6)
x

array([[1, 2, 3, 4, 5, 6]])

In [24]:
x=np.arange(1,7).reshape(1,6)
x,x.ndim,x.dtype,x.shape

(array([[1, 2, 3, 4, 5, 6]]), 2, dtype('int32'), (1, 6))

In [26]:
a=np.array([[1,2,3,4]])
a,a.ndim,a.dtype,a.shape

(array([[1, 2, 3, 4]]), 2, dtype('int32'), (1, 4))

### The numpy.linspace() function returns number spaces evenly w.r.t interval
### numpy.linspace(start, stop, num = 50, endpoint = True, 
### retstep = False, dtype = None)

In [31]:
x=np.linspace(0.1,1,50).reshape(10,5)
x

array([[0.1       , 0.11836735, 0.13673469, 0.15510204, 0.17346939],
       [0.19183673, 0.21020408, 0.22857143, 0.24693878, 0.26530612],
       [0.28367347, 0.30204082, 0.32040816, 0.33877551, 0.35714286],
       [0.3755102 , 0.39387755, 0.4122449 , 0.43061224, 0.44897959],
       [0.46734694, 0.48571429, 0.50408163, 0.52244898, 0.54081633],
       [0.55918367, 0.57755102, 0.59591837, 0.61428571, 0.63265306],
       [0.65102041, 0.66938776, 0.6877551 , 0.70612245, 0.7244898 ],
       [0.74285714, 0.76122449, 0.77959184, 0.79795918, 0.81632653],
       [0.83469388, 0.85306122, 0.87142857, 0.88979592, 0.90816327],
       [0.92653061, 0.94489796, 0.96326531, 0.98163265, 1.        ]])

In [32]:
x= np.array([[3,10,15,71],[7,4,5,9]])
x,x.shape

(array([[ 3, 10, 15, 71],
        [ 7,  4,  5,  9]]),
 (2, 4))

### This function reserves the dimension of the given array and returns the modified array.

In [34]:
x.transpose()

array([[ 3,  7],
       [10,  4],
       [15,  5],
       [71,  9]])

In [35]:
x.dot(x.transpose())

array([[5375,  775],
       [ 775,  171]])